### ISSUE TITLE
Installing Tatum

### ISSUE THREAD

**Issue by jobinblancaflor** [tatumio/tatum-kms#33]
I'm getting this error upon installation.
My Environment Versions: 
node: '14.15.4',
npm: '6.14.10',
![image](https://user-images.githubusercontent.com/16183139/163167639-b0fa042b-08b1-4fa6-9ddf-dd7d7b277b3e.png)

**Comment by a2600riz** [comment]
Same issue here
![Screenshot 2022-04-19 at 20 20 43](https://user-images.githubusercontent.com/20927371/163992592-52523e26-564e-43cc-bb0a-5f2708ecb8d1.png)

npm version:
```
{
  npm: '6.14.16',
  ares: '1.18.1',
  brotli: '1.0.9',
  cldr: '40.0',
  icu: '70.1',
  llhttp: '2.1.4',
  modules: '83',
  napi: '8',
  nghttp2: '1.42.0',
  node: '14.19.1',
  openssl: '1.1.1n',
  tz: '2021a3',
  unicode: '14.0',
  uv: '1.42.0',
  v8: '8.4.371.23-node.85',
  zlib: '1.2.11'
}
```

node version:
v14.19.1

**Comment by a2600riz** [comment]
> 

Ok I resolved this issue and the reason was "git" wasn't installed.

**Comment by PiusLucky** [comment]
Hey @jobinblancaflor. You should close this issue since it's resolved form your end.
