### ISSUE TITLE
Tatum daemon on https://api-us-west1.tatum.io 

### ISSUE THREAD

**Issue by manojCoe** [tatumio/tatum-kms#35]
I have a subscribed api key on region us-west1, when I'm trying to run tatum-kms daemon --api-key=XXXXXXX --chain=MATIC it is getting transactions on https://api-eu1.tatum.io/v3/kms/pending/MATIC?signatures=XXXXXX. Is there a way to change TATUM_API_URL using command line?

**Comment by kahwooi** [comment]
@manojCoe not sure if you have resolved the issue, but just for the benefits of others, the following is the solution for this issue:

Create an .env file with the following content:
```
TATUM_API_KEY=<Your Tatum API Key>
TATUM_API_URL=https://api-us-west1.tatum.io
```

Start the Tatum KMS in daemon mode:
`tatum-kms daemon --path=wallet.dat --testnet --chain=BTC  --period=10`

If you are using Docker,  run with the similar Docker command:
`docker run -d --env-file .env -v $HOME:/root/.tatumrc tatumio/tatum-kms daemon`
